---
locale: es
tags: [ ]
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
  - !ruby 
    value: '`"numero"`'
    checked: false
  - !ruby 
    value: "`8`"
    checked: false
  - !ruby 
    value: "`16`"
    checked: false
  - !ruby 
    value: "`20`"
    checked: true
  - !ruby 
    value: "`true`"
    checked: false
name: "¿Y esto cuánto vale?"
